name: newtouchme
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  flutter_native_splash: ^2.4.1
  google_maps_flutter: ^2.12.1
  permission_handler: ^11.0.0
  google_sign_in: ^6.1.5
  geolocator: ^12.0.0

  
  # ✅ Compatible Firebase packages for Flutter Web
  firebase_core: ^2.27.0
  firebase_core_web: ^2.10.0
  firebase_auth: ^4.17.0
  firebase_auth_web: ^5.8.5
  firebase_database: ^10.5.7
  js: ^0.6.7

  responsive_framework: ^0.2.0
  image_picker: ^1.0.4
  dropdown_search: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0



flutter_native_splash:
  image: assets/backgroundportrait.png  # Splash screen image
  color: "#ffffff"  # Background color
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:

    - assets/backgroundpotrait.png
    - assets/touchme.png
    - assets/vvhlogo.png
    - assets/whitebg.png
    - assets/p1i1.png
    - assets/p1i2.png
    - assets/p1i3.png
    - assets/continuousbutton.png
    - assets/continuousbutton2.png
    - assets/p2i1.png
    - assets/p2i2.png
    - assets/p2i3.png
    - assets/p3i1.png
    - assets/p3i2.png
    - assets/p3i3.png
    - assets/p3i4.png
    - assets/p3i5.png
    - assets/p4i1.png
    - assets/p4i2.png
    - assets/p4i3.png
    - assets/p4i4.png
    - assets/p4i5.png
    - assets/p4i6.png
    - assets/p4i7.png
    - assets/p4i8.png
    - assets/createaccount.png
    - assets/p5i1.png
    - assets/p5i2.png
    - assets/p5i3.png
    - assets/p5i4.png
    - assets/p5i5.png
    - assets/p5i6.png
    - assets/p5i7.png
    - assets/p5i8.png
    - assets/p5i9.png
    - assets/saloon_icon.png
    - assets/spa_icon.png
    - assets/customer_icon.png
    - assets/p6i1.png
    - assets/p6i2.png
    - assets/p6i3.png
    - assets/p6i4.png
    - assets/User.png
    - assets/eye.png
    - assets/lock.png
    - assets/eye_closed.png
    - assets/p7i1.png
    - assets/p7i_2.png
    - assets/location_on.png
    - assets/search.png
    - assets/p7i2.png
    - assets/p7i3.png
    - assets/p7i4.png
    - assets/p7i5.png
    - assets/p7i6.png
    - assets/p7i7.png
    - assets/p7i8.png
    - assets/p7i9.png
    - assets/p7i10.png
    - assets/home.png
    - assets/home_ash.png
    - assets/calender.png
    - assets/calender_ash.png
    - assets/search_color.png
    - assets/heart.png
    - assets/heart_ash.png
    - assets/person.png
    - assets/person_ash.png
    - assets/back.png
    - assets/next.png
    - assets/left_arrow.png
    - assets/dropdown.png
    - assets/filter.png
    - assets/visa.png
    - assets/paypal.png
    - assets/cash.png
    - assets/profile.png
    - assets/payment.png
    - assets/about.png
    - assets/logout.png
    - assets/circle.png
    - assets/left.png
    - assets/save.png
    - assets/like.png
    - assets/heartwhite.png
    - assets/heartpurple.png
    - assets/lotus.png
    - assets/glamour.png
    - assets/up.png
    - assets/down.png
    - assets/left_black.png
    - assets/portfolio.png
    - assets/gift.png
    - assets/niro.png
    - assets/reviews.png
    - assets/app_icon.png
    - assets/down-arrow.png
    - assets/sort.png
    - assets/services.png
    - assets/giftcards.png
    - assets/services_1.png
    - assets/services/nail.png
    - assets/services/hair.png
    - assets/services/makeup.png
    - assets/services/tattoo.png
    - assets/services/spa.png
    - assets/services/piercingg.png
    - assets/offers/offer1.png
    - assets/offers/offer2.png
    - assets/offers/offer3.png
    - assets/offers/offer4.png

    
  


