// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6rUrc39vX1AUhhmmD_O72-m2ME1lIkVs',
    appId: '1:874274913070:web:69059a8777987361db58bf',
    messagingSenderId: '874274913070',
    projectId: 'touch-me-47a76',
    authDomain: 'touch-me-47a76.firebaseapp.com',
    databaseURL: 'https://touch-me-47a76-default-rtdb.firebaseio.com',
    storageBucket: 'touch-me-47a76.firebasestorage.app',
    measurementId: 'G-6S1JLD5K4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD27bMgr6t8zkTM1kLO_4fX4QmBPOLII4',
    appId: '1:874274913070:android:6254a9a8b1019a65db58bf',
    messagingSenderId: '874274913070',
    projectId: 'touch-me-47a76',
    databaseURL: 'https://touch-me-47a76-default-rtdb.firebaseio.com',
    storageBucket: 'touch-me-47a76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHE963_aJ1ux1Rhb1d7gX8q3JPjEFCCpI',
    appId: '1:874274913070:ios:d47782a218bf07ccdb58bf',
    messagingSenderId: '874274913070',
    projectId: 'touch-me-47a76',
    databaseURL: 'https://touch-me-47a76-default-rtdb.firebaseio.com',
    storageBucket: 'touch-me-47a76.firebasestorage.app',
    iosBundleId: 'com.example.touchmeCs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHE963_aJ1ux1Rhb1d7gX8q3JPjEFCCpI',
    appId: '1:874274913070:ios:d47782a218bf07ccdb58bf',
    messagingSenderId: '874274913070',
    projectId: 'touch-me-47a76',
    databaseURL: 'https://touch-me-47a76-default-rtdb.firebaseio.com',
    storageBucket: 'touch-me-47a76.firebasestorage.app',
    iosBundleId: 'com.example.touchmeCs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6rUrc39vX1AUhhmmD_O72-m2ME1lIkVs',
    appId: '1:874274913070:web:8626a3c7386ba8e4db58bf',
    messagingSenderId: '874274913070',
    projectId: 'touch-me-47a76',
    authDomain: 'touch-me-47a76.firebaseapp.com',
    databaseURL: 'https://touch-me-47a76-default-rtdb.firebaseio.com',
    storageBucket: 'touch-me-47a76.firebasestorage.app',
    measurementId: 'G-3W3SP6XQSP',
  );
}
